### ISSUE TITLE
Upgrade you package to latest version of phpro/grumphp

### ISSUE THREAD

**Issue by gravataLonga** [drupol/php-conventions#3]
Hey you really need to upgrade this package to latest version of phpro/grumphp to the `0.18.1`.

**Comment by drupol** [comment]
This is something to do indeed, I will focus on this tonight :-)

**Comment by gravataLonga** [comment]
The latest version of phpro/grumphp support composer v2, which can be a big improve for you and for you package!

**Comment by drupol** [comment]
I need to do it :-) I'm just missing time :(

**Comment by gravataLonga** [comment]
Don't know if my pull request break something.. but i make a pull request, feel free to accepted or not!

**Comment by drupol** [comment]
yes, it will break `wearejust/grumphp-extra-tasks`, I need to remove that package and the related task. I will most probably do that tomorrow.

**Comment by gravataLonga** [comment]
Ahh ok! 👍

**Comment by drupol** [comment]
I just tagged 1.8.0, can you give me some feedback ?

**Comment by gravataLonga** [comment]
Ok, wil test! :)

**Comment by gravataLonga** [comment]
@drupol Finally grumphp it's work with composer v2!!! Thank you so much for rapid response and feedback!

**Comment by drupol** [comment]
Glad it works :)
